### ISSUE TITLE
RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version

### ISSUE THREAD

**Issue by mxmilkb** [whipper-team/whipper#400]
The first line of output when I run `whipper cd rip` is;

```
/usr/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
...
```

I have these installed:
- python2-chardet 3.0.4-2
- python2-urllib3 1.25.2-1

**Comment by Freso** [comment]
This is because you have installed `requests` (a Python library) which has hardcoded version dependencies and haven’t updated this to account for the recently updated `urllib3` to versions 1.25.x.

All in all, this is just a notice and a warning and won’t actually affect you (`urllib3` 1.25.x is perfectly API compatible with 1.24.x and thus works perfectly fine with latest `requests`). `requests` will have a new version Soon™ and the warning will go away.

See https://github.com/kennethreitz/requests/issues/5067 for discussion in upstream.
