### ISSUE TITLE
Properly tagging releases on dockerhub

### ISSUE THREAD

**Issue by thomas-mc-work** [whipper-team/whipper#423]
Currently there are only two dynamic tags on dockerhub: `latest` and `dev`. It'd be great to have every release of whipper being reflected as docker tags. E.g., `0.7`, `0.8`.

**Comment by JoeLametta** [comment]
Done!
Whipper started shipping a Dockerfile with version [v0.7.1](https://github.com/whipper-team/whipper/releases/tag/v0.7.1).
Docker tags available: [0.7.1, 0.7.2, 0.7.3, 0.8.0](https://hub.docker.com/r/whipperteam/whipper/tags) (all tagged versions since [v0.7.1](https://github.com/whipper-team/whipper/releases/tag/v0.7.1)).
I've also added a build rule for Docker Hub which should keep building future tagged releases automatically.
