### ISSUE TITLE
Missing .toc files when ripping a CD multiple times due to whipper ToC caching

### ISSUE THREAD

**Issue by the-confessor** [whipper-team/whipper#486]
Most of the CDs I have ripped with whipper have a .toc file, but a handful of them don't. I haven't been able to establish a pattern behind it.

What is the intended behavior - always create a .toc file, or only under certain conditions? If the latter then what are the conditions?

**Comment by JoeLametta** [comment]
> What is the intended behavior - always create a .toc file, or only under certain conditions?

Whipper should always* create the toc files: if it doesn't it means there's a bug somewhere...
* Caching information of already ripped CDs may cause this. If that's the case you can try deleting whipper's cache folder (`$XDG_CACHE_HOME/.cache/whipper/` or `~/.cache/whipper/`) and ripping again.

Is this reproducible multiple times against the same CD?

**Comment by the-confessor** [comment]
It is reproducible multiple times with the same CD.

Clearing the cache does work around the issue. 

I think I see a pattern. The affected rips are all ones where I ended up ripping the CD more than once. If I do the following I am able to reproduce the issue.
1. Rip a CD.
1. Inspect the ripped CD folder. Notice there is a .toc file.
1. Delete the ripped CD folder.
1. Rip the same CD again.
1. Inspect the ripped CD folder. This time there is not .toc file.

**Comment by JoeLametta** [comment]
Thanks for the test: that seems to confirm the caching hypothesis.
Relevant links:
- https://github.com/whipper-team/whipper/pull/321#issuecomment-437588821
- https://github.com/whipper-team/whipper/issues/335

**Comment by JoeLametta** [comment]
Hi, this should now be fixed thanks to [pull request 336](https://github.com/whipper-team/whipper/pull/336).

**Comment by pmoris** [comment]
I think this bug might have gotten re-introduced again somehow. I just tried to rip a CD twice in a row because some of its tracks couldn't be verified against AccurateRip. I renamed the first output folder before starting the second run. As described above, the second output folder lacked the .toc file.

EDIT: the tracks failed to be verified because they don't exist in the AccurateRip database, in case that matters. Incidentally, the terminal output confused me the first time around, because it simply stated that the rip was not accurate (with a confidence of 6), whereas the actual log file does mention that it's due to the album being missing from the database.

**Comment by MerlijnWajer** [comment]
@pmoris , this behaviour was seen on the latest develop branch?

**Comment by pmoris** [comment]
> [@pmoris](https://github.com/pmoris) , this behaviour was seen on the latest develop branch?

This was on v0.9.0 (the only machine I have with a functional cd-drive is still running Linux Mint 21.3). EDIT: v0.9.0 is what's reported by apt, `whipper --version` returns 0.0.0 for some reason.

I just tried to get the development version working, but got stuck trying to satisfy all the dependencies (specifically, I can't seem to install PyGObject because `libgirepository-2.0-dev` is unavailable). 

I could try the docker version if I find some time later on though.

**Comment by MerlijnWajer** [comment]
I haven't tested this PR yet, but I changed the dockerfile to use Debian trixie here: https://github.com/whipper-team/whipper/pull/668

**Comment by pmoris** [comment]
Issue seems to be gone when using the docker v.0.10.0!

**Comment by MerlijnWajer** [comment]
Ok, great, let's keep the issue closed then. Would you mind clarifying which Dockerfile you used in particular? The one from v 0.10.0 or the one I linked above?

**Comment by pmoris** [comment]
I tested using the v0.10.0 one (`docker pull whipperteam/whipper:latest` - [2199cc50eb35](https://hub.docker.com/layers/whipperteam/whipper/latest/images/sha256-2199cc50eb353412b97daa5bcf656f8e1d243f3608ab72ef2f45064a13b449b9)).

That being said, I had a hunch that the problem might not appear when using docker if it really is related to caching. So I tested it again just now using `docker pull whipperteam/whipper:0.9.0` and this time the .toc files all appear.

So I fear none of my tests are conclusive, unless I were to manage installing v0.10.0 from source.

EDIT: Since it's a relatively minor and obscure bug, just keep the issue closed unless someone else were to report similar probems :)
