### ISSUE TITLE
Document or implement option to avoid creating release type top-directory (e.g. 'album' / 'single')

### ISSUE THREAD

**Issue by Bujiraso** [whipper-team/whipper#520]
Hello,
I've recently started ripping CDs with whipper (do we call it "whipping"?! :thinking: ) and noticed that I get a new root directory called 'album' when I run `$ whipper cd rip`. Additionally, I put in a single and now I have another one named 'single'.

I configured `output_directory = ~/Music/` but I still end up with `~/Music/single/` when I rip a single.

I don't prefer these directories and would rather have them absent, but from a look through the code it doesn't seem these are hand-made by whipper but perhaps read from the TOC?
If that's the case then it may need to be implemented as I don't see this functionality.

If there is a feature for removing this, the documentation could use some additions to speak of it.

Let me know if some help pitching in on PR is desired. Thanks!

**Comment by JoeLametta** [comment]
Hi, whipper names files and directories according to the metadata obtained from MusicBrainz (unknown otherwise) and the implemented template schemes. Currently there are two schemes: one for the audio tracks, the other for the remaining disc files (.cue, .log, .m3u, etc.).
These are whipper's default values for the aforementioned templates:

```python
DEFAULT_TRACK_TEMPLATE = '%r/%A - %d/%t. %a - %n'
DEFAULT_DISC_TEMPLATE = '%r/%A - %d/%A - %d'
```

You can find the legend in whipper's man pages (or online [HERE](https://github.com/whipper-team/whipper/blob/develop/man/whipper-cd-rip.rst#template-schemes)).

**Comment by Bujiraso** [comment]
hi @JoeLametta, thanks for this intel, but I'm still not sure from the linked documentation how to override this.
The man page does not state these default templates, which could be good, nor does it state how to override them.

If it's as simple as putting it in ~/.config/whipper/whipper.conf, a line to that nature would be highly desirable

**Comment by Bujiraso** [comment]
:) still looking for an answer, if you can @JoeLametta

**Comment by 45054** [comment]
@Bujiraso It is documented at https://github.com/whipper-team/whipper#configuration-file-documentation with the correct section in whipper.conf where the template parameters are defined. If you remove the **%r/** parts out of the default example above, the release type should not be included anymore.

**Comment by Bujiraso** [comment]
Thanks @45054 !
