### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by mr-bo-jangles** [whipper-team/whipper#78]

**Comment by JoeLametta** [comment]
We thought about this but it's quite complicated, maybe in the future (just as an idea).

**Comment by RecursiveForest** [comment]
This is something we definitely want in my opinion, but it's pretty far away.

As an aside, "reactions" on GH are ridiculous.

**Comment by chrysn** [comment]
When this is implemented, I think that the (currently rather complex) concurrent Tasks can be simplified into asyncio Tasks. (I'm subscribing to this issue to be pinged when it becomes active).

**Comment by JoeLametta** [comment]
> When this is implemented, I think that the (currently rather complex) concurrent Tasks can be simplified into asyncio Tasks. (I'm subscribing to this issue to be pinged when it becomes active).

Yeah, there was a brief exchange about it [here](https://github.com/JoeLametta/whipper/issues/5#issuecomment-255300282).

**Comment by ArchangeGabriel** [comment]
JFYI, python2 is going to be definitively deprecated in around 3 years. So, even if it’s not tomorrow, this is indeed something that should be considered.

**Comment by Gibbz** [comment]
yes would like to see python3 support

**Comment by Freso** [comment]
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/2XDT6S62SEN4KGWQCOUYKXLBYVTKJ5VI/ was linked in the IRC channel and is about Fedora starting to drop packages that depend on Python 2 prior to Python 2 becoming unsupported upstream on Jan. 1st, 2020 (less than 2 years from now). If we want whipper to be shipped with Fedora, we may want to consider increasing the priority of porting the code to Py3.

**Comment by JoeLametta** [comment]
> If we want whipper to be shipped with Fedora, we may want to consider increasing the priority of porting the code to Py3.

You mean it would be wiser to reschedule this issue for milestone 1.0?

**Comment by Freso** [comment]
> You mean it would be wiser to reschedule this issue for milestone 1.0?

More like it should be one of the top priorities once 1.0 is out.

**Comment by mruszczyk** [comment]
RHEL is deprecating Python 2 support with RHEL 7.5 and thus Centos 7.5. My understanding is Python 2 will remain available until RHEL/Centos 8 but Python 3 has been swapped to the primary python.
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.5_release_notes/chap-red_hat_enterprise_linux-7.5_release_notes-deprecated_functionality

I'm not sure it matter much if at all because I'm not packaging in EPEL7 due to the very outdated libcdio-paranoia version but I just figured I'd throw the info in here.

**Comment by GHPS** [comment]
For quite some time I've been waiting for this port to Python 3 to happen. Since my system has no Legacy Python installed, whipper would be the only project that would rely on Python 2. So the progress here is good news...

Unfortunately I can't find any information on how usable the Python 3 version already is. Is it still experimental or ready for everyday use?

**Comment by JoeLametta** [comment]
> Unfortunately I can't find any information on how usable the Python 3 version already is. Is it still experimental or ready for everyday use?

Currently the python 3 version doesn't exist (I'm trying to incrementally update the code to make it compatible with both python 2 and python 3 - if easily doable). Unfortunately, as it is right now, whipper can't be used with python 3.

**Comment by GHPS** [comment]
Thanks for the update - keep up the good work!

**Comment by JoeLametta** [comment]
Just wanted to clarify that the aim of the port is to support only Python 3.

**Comment by GHPS** [comment]
So with the first Python 3 version the support for Legacy Python will be dropped?

**Comment by JoeLametta** [comment]
> So with the first Python 3 version the support for Legacy Python will be dropped?

[That's correct.](https://pythonclock.org/)

**Comment by tjaalton** [comment]
this is blocking whipper entering Debian & Ubuntu, py2 support is being removed from unstable, and no new packages that provide py2 modules (pycdio) or packages that depend on py2 (whipper) can enter the archive anymore

**Comment by tjaalton** [comment]
that probably sounded like a rant, sorry.. just stating the facts, I'll package it in a ppa for now :)

**Comment by mruszczyk** [comment]
Just tossing a note in here. Fedora is retiring Python2 once Fedora 31 is branched from Rawhide and any dependent packages (including whipper) will be removed 2 weeks before the Fedora 32 mass rebuild. 

https://fedoraproject.org/wiki/Changes/RetirePython2

I don't know if the Mass Rebuild date has been set, at least I cannot find one. Guessing off the dates from the Fedora 30 schedule, Fedora 31 is supposed to branch off rawhide next week we've got max 5 months before the package is removed before the Fedora 32 Mass Rebuild. 
https://fedoraproject.org/wiki/Releases/31/Schedule

**Comment by ArchangeGabriel** [comment]
Python 2 is EOL on December 31st, so yes most distros will drop it before this date. On Arch we are not decided yet, it will depend on whether there is anything big left unported, but the list is shrinking days after days.

**Comment by Freso** [comment]
Right now the focus is to get [0.8.0](https://github.com/whipper-team/whipper/milestone/4) made ready for release and pushed out, which will include [`python_requires` support](https://github.com/whipper-team/whipper/pull/378). Python 3 will be one of the top priorities after 0.8.0—which is currently only blocked by a couple of regressions compared to 0.7.x. If you want to help move whipper towards Python 3, consider giving a hand here:
https://github.com/whipper-team/whipper/milestone/4

**Comment by jwflory** [comment]
> I don't know if the Mass Rebuild date has been set, at least I cannot find one. Guessing off the dates from the Fedora 30 schedule, Fedora 31 is supposed to branch off rawhide next week, there's max 5 months before the package is removed before the Fedora 32 Mass Rebuild.
> https://fedoraproject.org/wiki/Releases/31/Schedule
> 

The Fedora 32 schedule is [now published](https://fedorapeople.org/groups/schedule/f-32/f-32-key-tasks.html). The Python 2 EOL is included for 1 January 2020. The F32 Mass Rebuild is scheduled from 22 Jan to 11 Feb 2020.

I am inclined to say that Py2 packages could be dropped between the Py2 EOL and the Mass Rebuild.

> A bug has filed against the package if anyone would like to comment on the timeline for this to the Fedora powers that be. https://bugzilla.redhat.com/show_bug.cgi?id=1739019

It's unlikely an exception will be approved. :disappointed: I didn't realize this blocked dropping the `python2-requests` package in Fedora. Perhaps as a short-term method, distributing [via COPR](https://copr.fedorainfracloud.org/) is an option, but it would be better to avoid dropping the package if at all possible. Setting up COPR with Py2 dependencies to work with Fedora would be a non-trivial amount of work because you also have to package `requests` for Python 2.

But I get this project is a volunteer-driven initiative too. If I can offer any advice or opinions from the Fedora/Linux packaging ecosystem POV, I'm happy to be a resource.

**Comment by ArchangeGabriel** [comment]
@jwflory There is an ongoing PR for porting at https://github.com/whipper-team/whipper/pull/411. There is one test failure remaining (https://github.com/whipper-team/whipper/pull/411#issuecomment-520791709) and several warnings/errors though.

**Comment by jwflory** [comment]
@ArchangeGabriel Thanks for pointing it out, I should have looked. :slightly_smiling_face: I left some feedback there.
